### ISSUE TITLE
When switch logger window into side bar, the view missed

### ISSUE THREAD

**Issue by sispd** [TorisanKitsune/Wider#38]
Itried the WiderMD program and open the logger window .
When I click "Auto Hide" button ,it acted as same as pic .
![2019-07-02 162942](https://user-images.githubusercontent.com/36954921/60492977-fb0f3600-9ce6-11e9-9c55-4814b6f0bec3.png)

**Comment by TorisanKitsune** [comment]
This issues showed up when Xceed was updated to 3.5.0. A theme adjustment should be able to fix this.

**Comment by sispd** [comment]
Oh,Thanks for answer the issue.
I saw the answer then I tried to searchsom theme library on nuget.
I found one and to replace Xceed.AvalonDock.Themes.VS2013  and  It works!
It seems fixed by other theme library named Dirkster.AvalonDock.Themes.VS2013

Thank you very much
